name: Status Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  status:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Health check
      run: |
        echo "🔍 Running health checks..."
        
        # Check Python version
        python --version
        
        # Check if main modules can be imported
        python -c "import main; print('✅ Main module OK')"
        python -c "import modules.fps_boost; print('✅ FPS Boost OK')"
        python -c "import modules.network_analyzer; print('✅ Network Analyzer OK')"
        python -c "import modules.ram_cleaner; print('✅ RAM Cleaner OK')"
        python -c "import modules.lol_optimizer; print('✅ LoL Optimizer OK')"
        
        # Check if build script exists
        if (Test-Path "build_simple_advanced.py") {
          echo "✅ Build script exists"
        } else {
          echo "❌ Build script missing"
          exit 1
        }
        
        # Check if main.py exists
        if (Test-Path "main.py") {
          echo "✅ Main application exists"
        } else {
          echo "❌ Main application missing"
          exit 1
        }
        
        echo "✅ All health checks passed"
        
    - name: Create status report
      run: |
        $status = @"
        # 🚀 NGXSMK GameNet Optimizer - Status Report
        
        **Build Date**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        **Python Version**: $(python --version)
        **Platform**: Windows
        **Status**: ✅ All systems operational
        
        ## Module Status
        - ✅ Main Application
        - ✅ FPS Boost Module
        - ✅ Network Analyzer Module
        - ✅ RAM Cleaner Module
        - ✅ LoL Optimizer Module
        - ✅ Build Scripts
        
        ## Next Steps
        - Ready for development
        - Ready for building
        - Ready for testing
        
        ---
        *Automated status check - $(Get-Date)*
        "@
        
        $status | Out-File -FilePath "STATUS_REPORT.md" -Encoding UTF8
        echo "📋 Status report created"
